;; 这是一个数据库配置的示例
;[database]
;host = localhost
;port = 3306
;user = root
;password = a_very_secret_password
;db_name = my_app_db
;
;# 空白节
;[empty_section]

# 服务器相关配置
[server]
ip_address = 192.168.182.129
port = 8563

[logging]
# 可选值: ERROR, WARNING, INFO, DEBUG (不区分大小写)
log_level = DEBUG

